apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: all
  description: A collection of all Backstage example entities, except users, groups, and templates
spec:
  targets:
    - ./all-templates.yaml
    - ./all-business-units.yaml
    # - ./all-apis.yaml
    # - ./all-components.yaml
    # - ./all-domains.yaml
    # - ./all-resources.yaml
    # - ./all-systems.yaml