apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: a-developer
  description: The Developer team of Business Unit A
  # annotations:
  #   backstage.io/description: The DevOps team of Business Unit A
  #   backstage.io/owner: business-unit-a
  #   backstage.io/techdocs-ref: url:techdocs:business-unit-a
  #   backstage.io/techdocs-ref-name: business-unit-a
spec:
  type: team
  profile:
    displayName: Developer - BU A
    email: a-developer@example.com
    picture: https://api.dicebear.com/7.x/identicon/svg?seed=Maggie&flip=true&backgroundColor=ffdfbf
  children: [blue, timi]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: blue
spec:
  profile:
    # Intentional no displayName for testing
    email: blue@example.com
    picture: https://api.dicebear.com/7.x/avataaars/svg?seed=Luna&backgroundColor=transparent
  memberOf: [a-developer]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: timi
spec:
  profile:
    # Intentional no displayName for testing
    email: timi@example.com
    picture: https://api.dicebear.com/7.x/avataaars/svg?seed=Luna&backgroundColor=transparent
  memberOf: [a-developer]
