apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name | dump }}
  annotations:
    github.com/project-slug: vvi11iam/backstage-environment
spec:
  type: service
  owner: ${{ values.owner | dump }}
  lifecycle: experimental
