
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: environment-destroy
  title: Environment Destroy
  description: An example template for the Developer Portal
spec:
  owner: group:default/a-devops
  type: service
  parameters:
    - title: Choose environment
      required:
        - componentId
      properties:
        componentId:
          title: Environment
          type: string
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              kind: Component
  steps:
    - id: github-action
      name: Trigger GitHub Action
      action: github:actions:dispatch
      input:
        workflowId: environment-destroy.yaml  # GitHub Action workflow ID
        repoUrl: 'github.com?repo=backstage-environment&owner=vvi11iam'
        branchOrTagName: 'main'  # The branch to run this action on
        workflowInputs:
          componentRepoOwner: vvi11iam
          componentId: ${{ parameters.componentId }}
          # clusterName: ${{ parameters.clusterName }}
          # awsRegion: ${{ parameters.region }}
          # action: ${{ parameters.action }}
          # apiName: ${{ parameters.environmentName }}
          # subdomain: ${{ parameters.environmentName }}

  output:
    text:
      - title: Information
        content: |
          Please wait a few minutes for the environment to be destroyed.

          The environment is being destroyed in the background.
          
          The component will be removed from the catalog on the next sync.

          **Deletion workflow:**
          https://github.com/vvi11iam/backstage-environment/actions/workflows/environment-destroy.yaml
